services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ih
      POSTGRES_PASSWORD: ih
      POSTGRES_DB: insighthouse
    # Use *named volumes* (melhor performance que bind mount no Windows/Mac)
    volumes:
      - ih_pg_data:/var/lib/postgresql/data
    command: >
      postgres -c shared_buffers=256MB
               -c work_mem=16MB
               -c maintenance_work_mem=128MB
               -c max_wal_size=2GB
               -c wal_compression=on
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ih -d insighthouse"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
    environment:
      # Database Configuration
      - DATABASE_URL=postgresql://ih:ih@db:5432/insighthouse?schema=public
      - DIRECT_URL=postgresql://ih:ih@db:5432/insighthouse?schema=public
      # Application Environment
      - PORT=3001
      - NODE_ENV=production
      - FRONTEND_URL=https://insighthouse.matheuscastroks.com.br
      # Authentication
      - NEXTAUTH_SECRET=CDJUGsX+5nKNX3ikSf1qQ/35jwxeG/+kya6T6zKP+cs=
      # API Configuration
      - API_BASE_URL=http://localhost:3001
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ih_pg_data:
